### ISSUE TITLE
libSDL2-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/redeclipse-appimage#3] opened 2017-02-12 22:21 UTC
Tried running `Red_Eclipse-1.5.8-x86_64.AppImage` on an otherwise unmodified `ubuntu-16.04-desktop-amd64.iso`:

```
me@host:~$ /home/me/Downloads/Red_Eclipse-1.5.8-x86_64.AppImage 
bin/amd64/redeclipse_linux: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

Interestingly, it is there:

```
me@host:~$ find  /tmp/.mount_mqE9yC | grep libSDL2-2.0.so.0
/tmp/.mount_mqE9yC/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
/tmp/.mount_mqE9yC/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.2.0
```

`AppRun` changes to the `usr/` directory, and then sets `LD_LIBRARY_PATH` to `LD_LIBRARY_PATH=./lib/:./lib/i386-linux-gnu/:./lib/x86_64-linux-gnu/:./lib32/:./lib64/:../lib/:../lib/i386-linux-gnu/:../lib/x86_64-linux-gnu/:../lib32/:../lib6`. Inspecting the AppImage with `strace` I see

```
[pid  4242] chdir("/tmp/.mount_9V95tF/usr/lib/redeclipse") = 0
```

Apparently redeclipse sets the current working directory to `usr/lib/redeclipse` inside the AppImage, and from that location, the relative `LD_LIBRARY_PATH`s cannot be resolved.

So you have (at least) two options here:
 1. Write your own launcher bash script called `AppRun` to replace the binary that is there at the moment, which would export absolute `LD_LIBRARY_PATH`s
 2. Symlink `lib/` into `usr/lib/redeclipse`, so that `usr/lib/redeclipse/lib/x86_64-linux-gnu/libSDL2-2.0.so.0` exists in the AppImage

Please let me know if something is unclear or doesn't make sense.

**Comment by probonopd** [comment] 2017-02-12 22:35
While you are at it, please move the libraries inside `usr/lib/x86_64-linux-gnu/pulseaudio/` on directory level up, as the `pulseaudio/` subdirectory is not on the `LD_LIBRARY_PATH`.

**Comment by probonopd** [comment] 2017-02-12 22:37
Finally, make sure that none of the libraries mentioned in https://github.com/probonopd/AppImages/blob/master/excludelist is bundled inside the AppImage. For example, if you bundle `libGL.so.1` then you can get errors like

```
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  91
  Current serial number in output stream:  92
```

An easy way to do this is something like this:

```
  BLACKLISTED_FILES=$(wget -q https://github.com/probonopd/AppImages/raw/master/excludelist -O - | sed '/^\s*$/d' | sed '/^#.*$/d')
  echo $BLACKLISTED_FILES
  for FILE in $BLACKLISTED_FILES ; do
    FOUND=$(find . -type f -name "${FILE}" 2>/dev/null)
    if [ ! -z "$FOUND" ] ; then
      echo "Deleting blacklisted ${FOUND}"
      rm -f "${FOUND}"
    fi
  done
```

**Comment by TheAssassin** [comment] 2017-02-13 13:10
Thanks for your suggestions. I am setting up a Debian testing VM that I can use for future tests before I upload new versions of the AppImage.

I have implemented the requested changes. However, on my host system (Ubuntu 16.04), the fact that `libGL.so.1` is missing in the AppImage causes the error that should actually be prevented by the change:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  112
  Current serial number in output stream:  113
```

As soon as I disable the blacklisting, the game starts normally.

**Comment by TheAssassin** [comment] 2017-02-13 13:21
Another issue: In the Debian VM, running the AppImage results in this error:

    bin/amd64/redeclipse_linux: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

I verified that the file is in the AppImage, just like the `lib` symlink.

Btw: about AppRun and `LD_LIBRARY_PATH`: Wouldn't it make more sense to resolve the full paths before having AppRun set the environment variable? This should be less error-prone, as the path wouldn't depend on the working directory any more, and the path won't change after the file system is mounted in `/tmp/.mount-something` anyway.

**Comment by TheAssassin** [comment] 2017-02-13 15:32
By accident, I found out that I already run the `delete_blacklisted` helper from `functions.sh`, but in the wrong directory. I just fixed that.

**Comment by TheAssassin** [comment] 2017-02-13 18:00
Looks like `libGL.so.1` and some other should be deleted by `delete_blacklisted`, but for some reason the script doesn't delete it. It does however delete all the otehr unwanted libraries. I am going to investigate that.

```
#### delete blacklisted libraries ####
libc.so.6 libdl.so.2 libstdc++.so.6 libm.so.6 libpthread.so.0 libresolv.so.2 libGL.so.1 libdrm.so.2 libxcb.so.1 libX11.so.6 libgio-2.0.so.0 libgdk-x11-2.0.so.0 libgtk-x11-2.0.so.0 libasound.so.2 libgdk_pixbuf-2.0.so.0 libfontconfig.so.1 libselinux.so.1 libcom_err.so.2 libcrypt.so.1 libexpat.so.1 libgcc_s.so.1 libglib-2.0.so.0 libgpg-error.so.0 libgssapi_krb5.so.2 libhcrypto.so.4 libhx509.so.5 libICE.so.6 libidn.so.11 libk5crypto.so.3 libkeyutils.so.1 libkrb5.so.26 libkrb5.so.3 libkrb5support.so.0 libm.so.6 libp11-kit.so.0 libpthread.so.0 libresolv.so.2 libroken.so.18 librt.so.1 libSM.so.6 libusb-1.0.so.0 libuuid.so.1 libwind.so.0 libz.so.1 libGL.so.1 libdrm.so.2 libgobject-2.0.so.0 libgpg-error.so.0 libxcb.so.1
Deleting blacklisted ./x86_64-linux-gnu/libc.so.6
Deleting blacklisted ./x86_64-linux-gnu/libdl.so.2
Deleting blacklisted ./x86_64-linux-gnu/libstdc++.so.6
Deleting blacklisted ./x86_64-linux-gnu/libm.so.6
Deleting blacklisted ./x86_64-linux-gnu/libpthread.so.0
Deleting blacklisted ./x86_64-linux-gnu/libresolv.so.2
Deleting blacklisted ./x86_64-linux-gnu/libexpat.so.1
Deleting blacklisted ./x86_64-linux-gnu/libgcc_s.so.1
Deleting blacklisted ./x86_64-linux-gnu/libglib-2.0.so.0
Deleting blacklisted ./x86_64-linux-gnu/libgpg-error.so.0
Deleting blacklisted ./x86_64-linux-gnu/libICE.so.6
Deleting blacklisted ./x86_64-linux-gnu/librt.so.1
Deleting blacklisted ./x86_64-linux-gnu/libSM.so.6
Deleting blacklisted ./x86_64-linux-gnu/libuuid.so.1
Deleting blacklisted ./x86_64-linux-gnu/libz.so.1
```

Edit: I can confirm that this is a bug in `delete_blacklist`, it should use `find -xtype f` instead of `find -type f` to also delete symlinks. I will create a PR in the AppImages repository.

**Comment by TheAssassin** [comment] 2017-02-13 19:42
> Write your own launcher bash script called AppRun to replace the binary that is there at the moment, which would export absolute LD_LIBRARY_PATHs

I just tested this, but I didn't have to replace AppRun. Since I already use a bash script to be able to set another environment variable, I was able to include `export LD_LIBRARY_PATH=$(readlink -f lib/)` in that script. I verified that it works by running `echo $LD_LIBRARY_PATH` right after the `export`.
Unfortunately, this does not fix the problem. Running the AppImage in the Debian VM still results in `bin/amd64/redeclipse_linux: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory`.
@probonopd, any ideas?

**Comment by probonopd** [comment] 2017-02-13 20:16
Are you sure that `LD_LIBRARY_PATH=$(readlink -f lib/)` works even when you call your script from another directory rather than from the one the script is in, and even if a `chdir` is subsequently done by the application? Wouldn't something along the lines of `HERE="$(dirname "$(readlink -f "${0}")")" ; LD_LIBRARY_PATH="${HERE}/lib/"` be needed?

**Comment by TheAssassin** [comment] 2017-02-13 20:57
I am pretty sure about that, yes. `readlink -f` returns the absolute path for the `lib` directory. Since `redeclipse` is run in the `usr` directory, the path is correct (e.g. `/tmp/.mount-something/usr/lib`). The `cd` command is run afterwards. The `echo $LD_LIBRARY_PATH` command is run after switching to `lib/redeclipse`.

**Comment by probonopd** [comment] 2017-02-13 21:00
Have it print out LD_LIBRARY_PATH, and make sure that it only contains absolute paths. Then run your app from the AppImage and see what the printed LD_LIBRARY_PATH says, and whether the library in question is in it.

An alternative to using LD_LIBRARY_PATH would be to [set the rpath](https://github.com/probonopd/AppImages/issues/89) using `patchelf`.

**Comment by TheAssassin** [comment] 2017-02-13 21:11
> Have it print out LD_LIBRARY_PATH, and make sure that it only contains absolute paths. Then run your app from the AppImage and see what the printed LD_LIBRARY_PATH says, and whether the library in question is in it.

Well, that's what I am doing at the moment. Sorry if that wasn't clear from my previous statements.

`redeclipse` script contents:
```
#! ./bin/bash

export REDECLIPSE_BRANCH=AppImage

export LD_LIBRARY_PATH=$(readlink -f lib/)
echo LD_LIBRARY_PATH before cd: $LD_LIBRARY_PATH

cd lib/redeclipse
echo LD_LIBRARY_PATH after cd: $LD_LIBRARY_PATH

exec bin/amd64/redeclipse_linux $@
```

Execution log:
```
user@host:~$ ./Red_Eclipse-1.5.8-x86_64.AppImage 
/bin/bash: ./lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
LD_LIBRARY_PATH before cd: /tmp/.mount_OpKSG0/usr/lib
LD_LIBRARY_PATH after cd: /tmp/.mount_OpKSG0/usr/lib
bin/amd64/redeclipse_linux: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

Anyway, I am going to test the `patchelf` variant tomorrow. I have to read a bit into that topic first.

**Comment by probonopd** [comment] 2017-02-13 21:13
Assuming that `libSDL2-2.0.so.0` is a x86_64 so file and is in `usr/lib` of the AppImage, that would indeed be _very_ strange.

**Comment by TheAssassin** [comment] 2017-02-13 21:20
Actually, the file is in `usr/lib/x86_64-linux-gnu`, which should be okay after reading the documentation for `LD_LIBRARY_PATH`. Might that be the problem?
I guess you've already seen this structure while you inspected the AppImage at first, so I assumed this was correct.

**Comment by probonopd** [comment] 2017-02-13 21:45
You can also put it into usr/lib/x86_64-linux-gnu but then you must have that on your LD_LIBRARY_PATH, too. Normally AppImage.c handles this, but here since the app does a chdir this is not sufficient.

**Comment by TheAssassin** [comment] 2017-02-14 00:40
Seems to work as intended now. I did not know that I had to explicitly add the `x86_64-linux-gnu` directory, too. I pushed fixes for this to the repository.

Unfortunately, this brought up a new error in the Debian VM:

```
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request: BadValue (integer parameter out of range for operation)
  ...
```

I'll have to investigate that tomorrow.

**Comment by probonopd** [comment] 2017-02-14 07:09
Is there an error message directly above that? See https://github.com/probonopd/AppImages/search?utf8=%E2%9C%93&q=swrast_dri.so

**Comment by TheAssassin** [comment] 2017-02-14 19:00
Nope, nothing related to that, just the warning about `libtinfo.so.5`:

    /bin/bash: ./lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)

**Comment by probonopd** [comment] 2017-02-14 19:02
Does it work in a non-VM environment?

**Comment by TheAssassin** [comment] 2017-02-14 19:03
Works fine on my host system.

**Comment by probonopd** [comment] 2017-02-14 19:05
Then my best guess at this point is that it's not working on VMs due to OpenGL driver issues. I may be wrong though.

**Comment by TheAssassin** [comment] 2017-02-14 19:06
I've tested it in a QEMU VM. I'll try in a VirtualBox, too.

**Comment by TheAssassin** [comment] 2017-02-15 22:23
Same error in the VirtualBox VM (running latest Debian Stretch 8.7.1 snapshot with guest extensions).

Running in a VM is not a real world usecase, but I'd like to have a test environment that doesn't involve running some distro on bare metal. But to resolve this issue, I'll run a live disk on another computer.

**Comment by TheAssassin** [comment] 2017-02-15 22:58
Error persists in a Ubuntu Studio 16.10 live DVD (I had that already), it even adds another error:

```
libGL error: unable to load driver: i965_dri.so`
...
```

As far as I can see, `swrast` is the fallback driver when the hardware driver is not available (`i965` apparently is the Intel HD graphics that is integrated into the CPU). I guess it doesn't happen on my host because the proprietary Intel drivers are there. I guess the AppImage would work on most computers in its current state, but there's Red Eclipse users that use the Intel chipset. I guess the AppImage shouldn't introduce any new issues.
This issue will have lower priority for me since it apparently works on "normal" computers. I am going to try to trace the issue down in the next days.

**Comment by TheAssassin** [comment] 2017-02-15 23:29
Another failing attempt:
I tried to dynamically resolve the `*_dri.so` directory and adding that to the `LD_LIBRARY_PATH`. That didn't work.
I also tried to add `libGL*` to the blacklist. I am not sure how SDL2 is built for Debian (the bugs occur as soon as Red Eclipse loads SDL), we might have to blacklist even more files. `libEGL` sounds like OpenGL-related stuff. `libX*` and `libwayland*` might have to be added, too.

**Comment by probonopd** [comment] 2017-02-16 06:48
Check out the Krita AppImage to see how they solved it.

**Comment by TheAssassin** [comment] 2017-02-17 14:37
Thanks for the suggestion @probonopd, this lead to the solution. The AppImage works just fine now in an unmodified Debian Stretch VM.

The Krita AppImage build script does not use the `delete_blacklisted` helper, instead they delete the libraries with a bunch of `rm` calls. Looking at what libraries they delete, I started to delete these libraries: `lib{xcb,GL,drm,X}*.so.*`. 

Relevant build log segment:

```
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-glx.so.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-present.so.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-render.so.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-shape.so.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-sync.so.1'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0.0.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libGL.so.1.2.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libGLESv2.so.2'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libGLESv2.so.2.0.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libGLU.so.1'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libdrm_intel.so.1'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libX11.so.6.3.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXau.so.6'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXau.so.6.0.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXcursor.so.1'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXdamage.so.1'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXdmcp.so.6'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXext.so.6'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXext.so.6.4.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXfixes.so.3'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXi.so.6'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXinerama.so.1'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXrandr.so.2'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXrender.so.1'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXss.so.1'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXtst.so.6'
removed `/workspace/redeclipse.AppDir/usr/lib/x86_64-linux-gnu/libXxf86vm.so.1'
```

Some of the files that would be matched by the pattern are already in the blacklist, but some others are not. I think they should go into the official blacklist though. I will start a discussion about that in the AppImageKit project.

But at least this issue is resolved.

**Closed as completed** 2017-02-17 14:37 UTC

**Comment by zion8992** [comment] 2025-01-11 14:08
just install libsdl
